name: rnase4
channels:
  - conda-forge
  - bioconda
  - pytorch
  - r
  - defaults
dependencies:
  - absl-py=2.1.0
  - adjusttext=1.2.0
  - anndata=0.10.8
  - annotated-types=0.7.0
  - anyio=4.4.0
  - aom=3.9.1
  - appnope=0.1.4
  - arpack=3.9.1
  - array-api-compat=1.7.1
  - arrow=1.3.0
  - asttokens=2.4.1
  - attrs=23.2.0
  - backoff=2.2.1
  - beautifulsoup4=4.12.3
  - blessed=1.19.1
  - blosc=1.21.6
  - boto3=1.34.145
  - botocore=1.34.145
  - brokenaxes=0.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.8.30
  - cachecontrol=0.14.0
  - cachecontrol-with-filecache=0.14.0
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - chex=0.1.86
  - cleo=2.1.0
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contextlib2=21.6.0
  - contourpy=1.2.1
  - crashtest=0.4.1
  - croniter=1.4.1
  - cycler=0.12.1
  - dateutils=0.6.12
  - dav1d=1.2.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - decoupler-py=1.7.0
  - deepdiff=7.0.1
  - distlib=0.3.8
  - dnspython=2.6.1
  - docrep=0.3.2
  - dulwich=0.21.7
  - email-validator=2.2.0
  - email_validator=2.2.0
  - et_xmlfile=1.1.0
  - etils=1.9.2
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - fastapi=0.111.1
  - fastapi-cli=0.0.4
  - filelock=3.15.4
  - flax=0.8.5
  - fonttools=4.53.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - future=1.0.0
  - get-annotations=0.1.2
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - igraph=0.10.13
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - inflect=7.3.1
  - inquirer=3.1.4
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - itsdangerous=2.2.0
  - jaraco.classes=3.4.0
  - jax=0.4.28
  - jaxlib=0.4.28
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.11
  - keyring=24.3.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - legacy-api-wrap=1.4
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libavif16=1.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libcxx=18.1.8
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libtorch=2.3.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning=2.0.9.post0
  - lightning-cloud=0.5.70
  - lightning-utilities=0.11.5
  - llvm-openmp=18.1.8
  - llvmlite=0.43.0
  - lxml=5.3.0
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - ml-collections=0.1.1
  - ml_dtypes=0.4.0
  - more-itertools=10.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - mudata=0.2.4
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - muon=0.1.6
  - natsort=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nomkl=1.0
  - numba=0.60.0
  - numpy=1.26.4
  - numpyro=0.15.1
  - omnipath=1.0.8
  - openjpeg=2.5.2
  - openpyxl=3.1.4
  - openssl=3.3.2
  - opt-einsum=3.3.0
  - opt_einsum=3.3.0
  - optax=0.2.2
  - orbax-checkpoint=0.4.4
  - ordered-set=4.1.0
  - orjson=3.10.6
  - packaging=24.1
  - pandas=1.5.3
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pkginfo=1.11.1
  - platformdirs=4.2.2
  - plotly=5.23.0
  - poetry=1.8.3
  - poetry-core=1.9.0
  - poetry-plugin-export=1.8.0
  - prompt-toolkit=3.0.47
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pybiomart=0.2.0
  - pycparser=2.22
  - pydantic=2.1.1
  - pydantic-core=2.4.0
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pynndescent=0.5.13
  - pyparsing=3.1.2
  - pyproject_hooks=1.1.0
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - python=3.11.9
  - python-annoy=1.17.3
  - python-build=1.2.1
  - python-dateutil=2.9.0
  - python-editor=1.0.4
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.6
  - python-installer=0.7.0
  - python-multipart=0.0.9
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.3.1
  - pytorch-lightning=2.3.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - rapidfuzz=3.9.4
  - rav1e=0.6.6
  - re2=2023.09.01
  - readchar=4.1.0
  - readline=8.2
  - requests=2.32.3
  - requests-toolbelt=1.0.0
  - requests_cache=0.4.13
  - rich=13.7.1
  - s3transfer=0.10.2
  - scanpy=1.10.2
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - scvi-tools=1.1.5
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - setuptools=71.0.4
  - shellingham=1.5.4
  - six=1.16.0
  - sleef=3.6.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sparse=0.15.4
  - stack_data=0.6.2
  - starlette=0.37.2
  - starsessions=1.3.0
  - statsmodels=0.14.2
  - stdlib-list=0.10.0
  - svt-av1=2.1.2
  - sympy=1.13.0
  - tbb=2021.12.0
  - tenacity=9.0.0
  - tensorstore=0.1.62
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.13.0
  - toolz=0.12.1
  - torchmetrics=1.4.0.post0
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - trove-classifiers=2024.7.2
  - typeguard=4.3.0
  - typer=0.12.3
  - typer-slim=0.12.3
  - typer-slim-standard=0.12.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - umap-learn=0.5.5
  - urllib3=2.2.2
  - uvicorn=0.30.3
  - virtualenv=20.26.3
  - wcwidth=0.2.13
  - websocket-client=1.8.0
  - websockets=12.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - xarray=2024.3.0
  - xattr=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - anndata2ri==1.3.1
      - bcrypt==4.2.0
      - biomart==0.9.2
      - boltons==24.0.0
      - cryptography==43.0.0
      - dill==0.3.8
      - face==20.1.1
      - fbpca==1.0
      - geosketch==1.2
      - glom==23.5.0
      - gseapy==1.1.3
      - intervaltree==3.1.0
      - json5==0.9.25
      - jsonpickle==3.2.2
      - memoir==0.0.3
      - multiprocess==0.70.16
      - paramiko==3.4.1
      - pycurl==7.45.3
      - pydeseq2==0.4.10
      - pynacl==1.5.0
      - pypath-common==0.2.4
      - pypath-omnipath==0.16.16
      - pyreadr==0.5.2
      - pysftp==0.2.9
      - pyvis==0.3.1
      - pywgcna==2.0.5
      - rdata==0.11.2
      - reactome2py==3.0.0
      - reprit==0.9.0
      - rpy2==3.5.16
      - rsrc==0.1.3
      - scanorama==1.7.4
      - sortedcontainers==2.4.0
      - sqlparse==0.5.1
      - tabulate==0.9.0
      - timeloop==1.0.2
      - toml==0.10.2
      - tzlocal==5.2
      - xlrd==2.0.1
